server:
  port: 7777
  servlet:
    context-path: /game-adapter

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: game-adapter
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    worker-id: ${random.int(1,31)}
    datacenter-id: ${random.int(1,31)}

management:
  server:
    port: 17777
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: debug
